   
<div class="register">
    <fieldset><legend>User Data</legend> 
        <form method="post" action="<?php echo $this->getFormAction(); ?>" class="scaffold-form">

            <label>   <?php echo $this->__('Title'); ?>  </label>  
            <input type="text" name="title"   value=""><br>
            <label>   <?php echo $this->__('  File Name'); ?>  </label>  

            <input type="text" name="filename"  value=""><br>

            <label>   <?php echo $this->__('Contents'); ?>  </label>  

            <input type="text" name="content" value=""><br>


            <label>  <?php echo $this->__('Status'); ?>  </label>  

            <select name="status" id= "status">
                <option value="1" >Enabled</option>
                <option value="2" >Disabled</option>
            </select>


            <input type="Submit" name="submit" value="<?php echo $this->__('Submit'); ?>">

        </form>
    </fieldset>
</div>

