<?php
$model = $this->fetchData();
?>

<table border='3' style='width:100%;' class="data-table cart-table" >
    <tr class="first last">
        <th>Id</th>
        <th>Title</th>
        <th>Content</th>
        <th>Status</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    <?php foreach ($model as $item) { ?>
        <tr>
            <td> <?php echo($item->getData('newtest_id')); ?></td>
            <td> <?php echo($item->getData('title')); ?></td>
            <td> <?php echo($item->getData('content')); ?></td>
            <td><?php echo($item->getData('status')); ?></td>
            <td> <a href="index/update?edit_id=<?php echo($item->getData('newtest_id')); ?>">Update</a></td>
            <td> <a href="?id=<?php echo($item->getData('newtest_id')); ?>">Delete</a></td>

        </tr>

    <?php } ?>
</table>
<a href="index/insert">Add New Row</a>







































<?php
/*
  This shows how to load specific fields from a record in the database.
  1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
  2) You can then just use the get(fieldname) to pull specific data from the table.
  3) If you have a field named news_id, then it becomes getNewsId, etc.
 */
/*
  $news = Mage::getModel('newtest/newtest')->load(15);
  echo $news->getNewsId();
  echo $news->getTitle();
  echo $news->getContent();
  echo $news->getStatus();
 */

/*
  This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
  Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

 */
/*
  $object = $this->getNewtest();
  echo 'id: '.$object['test_id'].'<br/>';
  echo 'title: '.$object['title'].'<br/>';
  echo 'content: '.$object['content'].'<br/>';
  echo 'status: '.$object['status'].'<br/>';
 */


/*
  This shows how to load multiple rows in a collection and save a change to them.
  1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
  2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
 */
/*
  $i = 0;

  $collection = Mage::getModel('newtest/newtest')->getCollection();
  $collection->setPageSize(5);
  $collection->setCurPage(2);
  $size = $collection->getSize();
  $cnt = count($collection);
  foreach ($collection as $item) {
  $i = $i+1;
  $item->setTitle($i);
  echo $item->getTitle();
  }

  $collection->walk('save');
 */

/*
  This shows how to load a single record and save a change.
  1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
  2) Call the save() function only on a single record.
 */
/*
  $object = Mage::getModel('newtest/newtest')->load(1);
  $object->setTitle('This is a changed title');
  $object->save();
 */
?> 



