

<?php
$model = $this->fatchData();
?>


<table border='3' style='width:100%;' class="data" >
    <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Content</th>
        <th>Status</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    <?php foreach ($model as $item) { ?>
        <tr>
            <td> <?php echo($item->getData('test_id')); ?></td>
            <td> <?php echo($item->getData('title')); ?></td>
            <td> <?php echo($item->getData('content')); ?></td>
            <td><?php echo($item->getData('status')); ?></td>
            <td> <a href="?edit_id=<?php echo($item->getData('test_id')); ?>">Update</a></td>
            <td> <a href="?id=<?php echo($item->getData('test_id')); ?>">Delete</a></td>

        </tr>

    <?php } ?>
</table>


<br><br><br><br>
<div class="register">

    <form method="post"action="" class="scaffold-form">
        <fieldset><legend>User Data</legend> 
            <?php echo $this->__('Title') ?>
            <input type="text" name="title" value="<?php
            if (!empty($title)) {
                echo $title;
            }
            ?>"><br>
            File Name:
            <input type="text" name="filename"  value="<?php
            if (!empty($filename)) {
                echo $filename;
            }
            ?>"><br>
            Contents:
            <input type="text" name="contents" value="<?php
            if (!empty($content)) {
                echo $content;
            }
            ?>"><br>
            Status:


            <input type="text" name="status" value="<?php
            if (!empty($status)) {
                echo $status;
            }
            ?>"><br>



            <input type="Submit" name="submit" value="<?php echo $this->__('submit') ?>">
            <?php if (!empty($id)) { ?>

                <input type="Submit" name="update" value="<?php echo $this->__('update') ?>">


            <?php } ?> 

        </fieldset>
    </form>
</div>














